graph TB
    style S1 stroke-width:4px
    style S6 fill:#0f0,stroke-width:4px
    style S10 fill:#0f0
    style S11 fill:#0f0
    S1 --- S2
    S1 --- S3
    S1 --- S4
    S2 --- S5
    S2 --- S6
    S3 --- S7
    S3 --- S8
    S4 --- S9
    S6 --- S10
    S6 --- S11