# ----------------------------------------------------------------------
# DefaultServiceItem
# ----------------------------------------------------------------------
# Copyright (C) 2007-2021 The NOC Project
# See LICENSE for details
# ----------------------------------------------------------------------

# Python modules
from typing import Optional

# Third-party modules
from pydantic import BaseModel

# NOC modules
from .utils import Reference


class LabelItem(BaseModel):
    id: str
    name: str
    is_protected: bool
    scope: str
    value: str
    bg_color1: str
    fg_color1: str
    bg_color2: str
    fg_color2: str


class DefaultLabelItem(BaseModel):
    id: str
    name: str
    description: Optional[str]
    bg_color1: Optional[int]
    fg_color1: Optional[int]
    bg_color2: Optional[int]
    fg_color2: Optional[int]
    is_protected: Optional[bool]
    is_autogenerated: Optional[bool]
    enable_agent: Optional[bool]
    enable_service: Optional[bool]
    enable_serviceprofile: Optional[bool]
    remote_system: Optional[Reference]
    # Object id in remote system
    remote_id: Optional[str]
